import _extends from "@babel/runtime/helpers/esm/extends";
import { BaseWidgetProps } from "../common/base_props";
export var CollectionWidgetItem = {};
export var ToolbarButtonGroupItemProps = _extends({}, CollectionWidgetItem);
export var ToolbarButtonGroupItemPropsType = {};
export var ToolbarButtonGroupProps = {};
export var ToolbarButtonProps = {};
export var ToolbarDropDownButtonItemProps = _extends({}, CollectionWidgetItem);
export var ToolbarDropDownButtonItemPropsType = {};
export var ToolbarDropDownButtonProps = {};
export var ToolbarItemOptionType = {};
export var ToolbarItem = _extends({}, CollectionWidgetItem);
export var ToolbarItemType = {};
export var ToolbarProps = _extends({}, BaseWidgetProps);